// Kuratierte Vorschlagslisten fuer die Material-/Hersteller-Felder im
// Filament-Katalog (siehe FilamentView.tsx). Alphabetisch sortiert, dienen
// nur als Autocomplete-Vorschlag ueber <datalist> - beide Felder bleiben
// freie Texteingaben, damit exotische/eigene Werte weiterhin moeglich sind.

export const FILAMENT_MATERIALS: string[] = [
  'ABS',
  'ASA',
  'BVOH',
  'HIPS',
  'Nylon (PA)',
  'Nylon-CF',
  'PC (Polycarbonat)',
  'PC-ABS',
  'PCTG',
  'PEEK',
  'PEI (Ultem)',
  'PETG',
  'PETG-CF',
  'PLA',
  'PLA (Glow in the Dark)',
  'PLA (Matte)',
  'PLA (Metall-gefuellt)',
  'PLA (Silk)',
  'PLA (Holz-gefuellt)',
  'PLA+',
  'PLA-CF',
  'PP (Polypropylen)',
  'PVA',
  'TPU (85A, flexibel)',
  'TPU (95A, flexibel)',
];

export const FILAMENT_MANUFACTURERS: string[] = [
  '3DJake',
  '3DXTech',
  'Amolen',
  'Anycubic',
  'Azure Film',
  'Bambu Lab',
  'ColorFabb',
  'Creality',
  'Das Filament',
  'Devil Design',
  'eSUN',
  'Extrudr',
  'Fiberlogy',
  'Fillamentum',
  'Filatech',
  'Formfutura',
  'GEEETECH',
  'Hatchbox',
  'Innofil3D (BASF)',
  'Kimya',
  'MatterHackers',
  'Overture',
  'Paramount 3D',
  'Polymaker',
  'Priline',
  'Proto-pasta',
  'Prusament',
  'Real Filament',
  'Recreus',
  'Smartfil',
  'Spectrum Filaments',
  'SUNLU',
  'Taulman3D',
  'TTYT3D',
  'Ultimaker',
  'Verbatim',
  'ZIRO',
];
