#!/bin/sh
set -eu
# The filesystem warning must come first: auth can fail on NFS/CIFS where chown is refused.
/usr/local/libexec/3mf-filesystem
/usr/local/libexec/3mf-auth
install -d -m 755 -o abc -g abc /run/3mf
rm -f /run/3mf/app.pid
